### ISSUE TITLE
Compile on non-linux systems fails

### ISSUE THREAD

**Issue by orr721** [Seeker04/srek#1]
Hi, this looks very interesting to me. But how would I compile it on any non-linux system? As far as I know sys/prctl.h is a linux-ism and it is not present/possible on e.g. Mac OS, Illumos/Solaris (and you do mention Solaris 10 in the README).. I do not see any relevant options in the Makefile. Thanks!

```
gmake
cc -c -std=c89 -ansi -pedantic -pedantic-errors -W -Wall -Wextra -Wconversion -Wfloat-equal -Wshadow -O3 -D_POSIX_C_SOURCE=2 srek.c -o srek.o
srek.c:23:23: fatal error: sys/prctl.h: No such file or directory
 #include <sys/prctl.h>
                       ^
compilation terminated.
gmake: *** [Makefile:39: srek.o] Error 1
```

**Comment by Seeker04** [comment]
Hello!

You are totally right about prctl.h not being portable. Fortunatelly, it isn't a heavy dependency, since it's only used at one place in the `|` command's code:
`prctl(PR_SET_PDEATHSIG, SIGTERM); /* send SIGTERM if the parent dies */`
And this is only a "just in case" way of ensuring the child is killed gracefully if the parent (srek) prematurely dies for some reason, which should never really happen...

I've added an `#if __linux__` check for this feature, so no commenting out or fiddling with the compile options is required to build this on other systems.

I rechecked on Solaris 10, it does compile now with no errors. I have no current access to a BSD or Mac (and am too lazy to setup vms just to check this), but they should be fine too.

Thanks for the feedback!:)
And let me know if you have other troubles compiling this on some system.
